# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: ./gradlew build -x test
    - name: Test
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: ./gradlew test

